# MOwNiT - Wybrane zagadnienia algebry liniowej i faktoryzacja

Biblioteką w pythonie do algebry liniowej są:
- `numpy.linalg` https://numpy.org/doc/stable/reference/routines.linalg.html
- `scipy.linalg` https://docs.scipy.org/doc/scipy/reference/linalg.html


In [8]:
import numpy as np
import scipy as sc

### Sposoby rozwiązania równań macierzowych Ax=b

In [4]:
A=np.random.randint(0,10,(4,4))
print(A)

b=np.random.randint(0,10,4)
print(b)

[[1 9 7 0]
 [2 2 1 0]
 [2 1 5 1]
 [8 4 3 9]]
[1 9 4 5]


Metoda macierzy odwrotnej:
$$Ax=b\ \Rightarrow\ x=A^{-1}b$$

In [5]:
#mozemy policzyc odwrotność macierzy i wymnożyć
# uwaga: nieefektywne!
(np.linalg.inv(A)).dot(b)

array([ 4.81430746, -0.11719939, -0.39421613, -3.54033486])

In [7]:
#najlepiej używać dedykowanej funkcji solve
x=np.linalg.solve(A,b)
print(x)

[ 4.81430746 -0.11719939 -0.39421613 -3.54033486]


### Faktoryzacja LU

In [10]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
P,L,U=sc.linalg.lu(A)
print(P) #macierz permutacji
print(L) #dolna trójkątna
print(U) #górna trójkątna

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
[[ 1.          0.          0.          0.        ]
 [ 0.125       1.          0.          0.        ]
 [ 0.25        0.          1.          0.        ]
 [ 0.25        0.11764706 -0.12456747  1.        ]]
[[ 8.         4.         3.         9.       ]
 [ 0.         8.5        6.625     -1.125    ]
 [ 0.         0.         4.25      -1.25     ]
 [ 0.         0.         0.        -2.2733564]]


### Faktoryzacja QR


In [16]:
B=np.random.randint(0,10,(10,5))
print(B)

[[4 5 7 0 8]
 [9 3 0 6 2]
 [3 4 0 4 8]
 [9 3 8 2 5]
 [1 0 7 5 9]
 [2 5 6 0 0]
 [9 9 9 8 2]
 [5 4 6 2 4]
 [6 8 3 6 7]
 [0 1 6 3 1]]


In [17]:
# Domyślna faktoryzacja QR macierzy MxN zwraca Q wymiaru MxK, R wymiaru KxN gdzie K=min(M,N)

Q,R=np.linalg.qr(B)
print(Q)
print(R)

[[-0.21887026  0.25374463  0.22259129 -0.40923099 -0.44023792]
 [-0.49245809 -0.44239824 -0.35995721  0.20845015  0.09389632]
 [-0.1641527   0.22101525 -0.2759524   0.22421227 -0.49565036]
 [-0.49245809 -0.44239824  0.29512644 -0.34353458 -0.09226386]
 [-0.05471757 -0.09009773  0.55053258  0.5629921  -0.37221924]
 [-0.10943513  0.43394009  0.18603707 -0.30196359  0.2305165 ]
 [-0.49245809  0.29456442  0.06507858  0.21968674  0.50887195]
 [-0.27358783  0.04081979  0.17002911 -0.16349326 -0.05037425]
 [-0.32830539  0.4420305  -0.30624843  0.17687794 -0.19726326]
 [-0.          0.12282711  0.43932385  0.3261459   0.22606661]]
[[-18.27566688 -13.40580355 -13.56995625 -11.32653606 -11.38125363]
 [  0.           8.14152511   5.1690355    2.35320562   3.85986032]
 [  0.           0.          12.21218078   0.42053077   4.38948065]
 [  0.           0.           0.           7.74565414   3.63569857]
 [  0.           0.           0.           0.         -11.44913533]]


In [18]:
# jeżeli chcemy otrzymać Q wymiaru MxM, R wymiaru MxN trzeba wybrać mode=`complete`
Qc,Rc=np.linalg.qr(B,mode='complete')
print(Qc)
print(Rc)

[[-0.21887026  0.25374463  0.22259129 -0.40923099 -0.44023792 -0.27435974
  -0.42329466 -0.30935987 -0.31406823 -0.16759813]
 [-0.49245809 -0.44239824 -0.35995721  0.20845015  0.09389632  0.30321144
  -0.50161342 -0.0590184  -0.17100123 -0.06044711]
 [-0.1641527   0.22101525 -0.2759524   0.22421227 -0.49565036  0.16732242
   0.35231437  0.081722   -0.43998991  0.44690513]
 [-0.49245809 -0.44239824  0.29512644 -0.34353458 -0.09226386 -0.01406895
   0.38155932 -0.17606284  0.28125839  0.30372804]
 [-0.05471757 -0.09009773  0.55053258  0.5629921  -0.37221924  0.24123571
   0.07418134 -0.02938312  0.07540574 -0.40006007]
 [-0.10943513  0.43394009  0.18603707 -0.30196359  0.2305165   0.78539726
  -0.01619574 -0.05754836  0.01530658  0.01153396]
 [-0.49245809  0.29456442  0.06507858  0.21968674  0.50887195 -0.30425828
   0.32408513 -0.11788999 -0.29672961 -0.24437246]
 [-0.27358783  0.04081979  0.17002911 -0.16349326 -0.05037425 -0.08266825
  -0.10931124  0.91762926 -0.02300061 -0.06285275]


### Zastosowanie faktoryzacji do metody najmniejszych kwadratów

Jednym z zastosowań faktoryzacji QR jest użycie jej do metody najmniejszych kwadratów.

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=a_2*x^2+a_1*x+a_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$a_2x_i^2+a_1x_i+a_0=y_i$$:
$$a_2*1^2+a_1*1+a_0=1$$
$$a_2*2^2+a_1*2+a_0=2$$
$$a_2*3^2+a_1*3+a_0=4$$
$$a_2*4^2+a_1*4+a_0=4$$
$$a_2*5^2+a_1*5+a_0=3$$
$$a_2*6^2+a_1*6+a_0=0$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znaleźć najlepsze przybliżenie, czyli takie $a_i$, które minimalizują odległość:

$$\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}=\lVert y-A*a\rVert$$





Jak użyć do tej mimalizacji faktoryzacji QR:

1. Tworzymy macierz A współczynników równania

2. Dokonujemy faktoryzacji QR macierzy A 

3. Mamy równanie:
$$A*a=y$$
Dla $A=QR$:
$$QR*a =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*a =Q^T y$$
$$\begin{pmatrix} R \\ 0 \end{pmatrix} a= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$R * a= Q^T y[1:n]$$
$$a=R \setminus Q^T y[1:n]$$

Więcej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

## Zadanie 1 (2pkt)
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x.
Nastepnie rozwiąż równanie Ax=b trzema metodami:
- metodą macierzy odwrotnej
- funkcją `solve`
- z wykorzystaniem wybranej faktoryzacji

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@timeit).

In [ ]:
#TYPE YOUR CODE BELOW



## Zadanie 2 (1pkt)
Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda z użyciem faktoryzacji QR zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

In [ ]:
#TYPE YOUR CODE BELOW



## Zadanie 3 (2 pkt)

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

-    tworzenie pseudoinversji macierzy (http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

-   uzycie faktoryzacji QR do znajdowania wartości własnych (https://en.wikipedia.org/wiki/QR_algorithm)

-  zastosowanie faktoryzacji SVD - np. zastosowania w uczeniu maszynowym 

In [ ]:
#TYPE YOUR CODE BELOW

